services:
  live:
    build: .
    image: live-webrtc-go:latest
    restart: unless-stopped
    environment:
      - HTTP_ADDR=:8080
      - ALLOWED_ORIGIN=*
      - RECORD_ENABLED=1
      - RECORD_DIR=/records
      - STUN_URLS=stun:stun.l.google.com:19302
      # 若启用 TURN，请设置以下两项并确保 coturn 配置一致
      # - TURN_URLS=turn:coturn:3478?transport=udp
      # - TURN_USERNAME=user
      # - TURN_PASSWORD=pass
    ports:
      - "8080:8080"
    volumes:
      - ./records:/records
    # depends_on:
    #   - coturn

  # 示例 TURN 服务（可选）。生产请根据安全需求配置。
  # coturn:
  #   image: instrumentisto/coturn
  #   restart: unless-stopped
  #   command: [
  #     "--no-cli", "--no-tls", "--no-dtls",
  #     "--listening-port", "3478",
  #     "--min-port", "49152", "--max-port", "49252",
  #     "--lt-cred-mech",
  #     "--user", "user:pass",
  #     "--realm", "localhost"
  #   ]
  #   ports:
  #     - "3478:3478/udp"
  #     - "3478:3478/tcp"
  #     - "49152-49252:49152-49252/udp"
